# Generated by Django 2.2.2 on 2019-06-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyResult', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
