# Generated by Django 2.2.2 on 2019-06-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlel', models.CharField(default='Something defult titel', max_length=500)),
                ('items', models.CharField(default='Something defult item', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField(default='Something defult ansewr', max_length=500)),
                ('is_results', models.BooleanField(default=False)),
                ('surveys', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='survey.Surveys')),
            ],
        ),
    ]
