# Generated by Django 2.2.2 on 2019-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verksamhetsstyrning', models.IntegerField(blank=True, default='Something default verksam')),
                ('engagemang', models.IntegerField(blank=True, default='Something default eve')),
                ('resurser', models.IntegerField(blank=True, default='Something default resurs')),
                ('kommunikation', models.IntegerField(blank=True, default='Something default kommun')),
            ],
        ),
        migrations.RemoveField(
            model_name='surveys',
            name='items',
        ),
        migrations.RemoveField(
            model_name='surveys',
            name='titlel',
        ),
        migrations.AddField(
            model_name='surveys',
            name='questionID',
            field=models.CharField(default='Something default ID', max_length=500),
        ),
        migrations.AddField(
            model_name='surveys',
            name='questionLabel',
            field=models.CharField(choices=[('text', 'short_text'), ('text', 'long_text'), ('text', 'dropdown'), ('choice.label', 'multiple_choice (single option)'), ('choice.labels', 'multiple_choice (multiple options)'), ('choice.label', 'picture_choice (single option)'), ('choice.labels', 'picture_choice (multiple options)'), ('email', 'email'), ('url', 'website'), ('file_url', 'file_upload'), ('boolean', 'legal'), ('boolan', 'yes_no'), ('number', 'rating'), ('number', 'opinion_scale'), ('number', 'number'), ('date', 'date')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='surveys',
            name='questionMaxPoints',
            field=models.IntegerField(default='Something default MAXpoints'),
        ),
        migrations.AddField(
            model_name='surveys',
            name='questionPoints',
            field=models.IntegerField(blank=True, default='Something default Points'),
        ),
        migrations.AddField(
            model_name='surveys',
            name='questionType',
            field=models.CharField(default='Something default item', max_length=500),
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
