# Generated by Django 2.2.2 on 2019-06-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='engagemang',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='kommunikation',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='resurser',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='verksamhetsstyrning',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
