# Generated by Django 2.2.2 on 2019-06-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_Id',
            field=models.CharField(help_text='Add the Survey ID from Typefrom here', max_length=20),
        ),
    ]
