# Generated by Django 2.2.2 on 2019-06-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190623_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveys',
            name='questionLabel',
        ),
        migrations.AddField(
            model_name='surveys',
            name='questionAnswer',
            field=models.CharField(default='Exact answer goes here', max_length=500),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='questionID',
            field=models.CharField(default='Question ID from Typefrom goes here', max_length=500),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='questionType',
            field=models.CharField(choices=[('text', 'short_text'), ('text', 'long_text'), ('text', 'dropdown'), ('choice.label', 'multiple_choice (single option)'), ('choice.labels', 'multiple_choice (multiple options)'), ('choice.label', 'picture_choice (single option)'), ('choice.labels', 'picture_choice (multiple options)'), ('email', 'email'), ('url', 'website'), ('file_url', 'file_upload'), ('boolean', 'legal'), ('boolan', 'yes_no'), ('number', 'rating'), ('number', 'opinion_scale'), ('number', 'number'), ('date', 'date')], max_length=20),
        ),
    ]
