# Generated by Django 2.2.2 on 2019-06-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190625_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='current_Points',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Displaying current points. DO NOT CHANGE THIS.', max_digits=5, null=True),
        ),
    ]
