# Generated by Django 2.2.2 on 2019-06-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190623_1616'),
    ]

    operations = [
    ]
