# Generated by Django 2.2.2 on 2019-06-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190623_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='engagemang',
            field=models.IntegerField(blank=True, default=0, help_text="Don't change this value"),
        ),
        migrations.AlterField(
            model_name='score',
            name='kommunikation',
            field=models.IntegerField(blank=True, default=0, help_text="Don't change this value"),
        ),
        migrations.AlterField(
            model_name='score',
            name='resurser',
            field=models.IntegerField(blank=True, default=0, help_text="Don't change this value"),
        ),
        migrations.AlterField(
            model_name='score',
            name='verksamhetsstyrning',
            field=models.IntegerField(blank=True, default=0, help_text="Don't change this value"),
        ),
    ]
