# Generated by Django 2.2.2 on 2019-06-28 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190625_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_Id', models.CharField(help_text='Add the Survey ID from Typefrom here', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='survey',
            field=models.ForeignKey(blank=True, help_text='Choose what Survey thos Category belogs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Choose to what Category this question belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_Points',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Make sure that this is not higher then Max Points for the catagory. {Category.max_Points}', max_digits=5),
        ),
    ]
