# Generated by Django 2.2.2 on 2019-06-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190623_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Surveys',
            new_name='Survey',
        ),
    ]
