# Generated by Django 2.2.2 on 2019-06-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190623_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionMaxPoints',
            new_name='question_Max_Points',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionPoints',
            new_name='question_Points',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionType',
            new_name='question_Type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionAnswer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionID',
        ),
        migrations.AddField(
            model_name='question',
            name='question_Answer',
            field=models.CharField(blank=True, help_text='Exact answer goes here', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_ID',
            field=models.CharField(blank=True, help_text='Question ID from Typefrom goes here', max_length=500, null=True),
        ),
    ]
