# Generated by Django 2.2.2 on 2019-06-24 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190624_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='survey',
            field=models.ForeignKey(blank=True, help_text='Choose what Survey the category belogs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catagory', to='survey.Survey'),
        ),
    ]
