# Generated by Django 2.2.2 on 2019-06-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190623_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveys',
            old_name='questionType',
            new_name='questionTypes',
        ),
        migrations.AlterField(
            model_name='score',
            name='engagemang',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='kommunikation',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='resurser',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='verksamhetsstyrning',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='questionMaxPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='questionPoints',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
