# Generated by Django 2.2.2 on 2019-06-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190628_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='current_Points',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Displaying current points. DO NOT CHANGE THIS.', max_digits=5, null=True),
        ),
    ]
