# Generated by Django 2.2.2 on 2019-07-08 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20190628_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, help_text='Important that this is exact', max_length=500, null=True)),
                ('points', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='points for this answer', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.CharField(help_text="Autofield response id from hidden field in Typeform. Don't change this", max_length=100, primary_key=True, serialize=False)),
                ('verksamhetsstyrning', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Points for this category', max_digits=5)),
                ('engagemang', models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Points for this category', max_digits=5)),
                ('resurser', models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Points for this category', max_digits=5)),
                ('kommunikation', models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Points for this category', max_digits=5)),
                ('survey', models.ForeignKey(blank=True, help_text='Choose what Survey thiss Answer belogs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_Answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_Points',
        ),
        migrations.AlterField(
            model_name='category',
            name='survey',
            field=models.ForeignKey(blank=True, help_text='Choose what Survey this Category belogs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, help_text='Choose to what Question the Answer belongs tobelongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
    ]
