# Generated by Django 2.2.2 on 2019-07-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20190708_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='survey',
        ),
        migrations.AlterField(
            model_name='answer',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='points for this answer', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='engagemang',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Points for this category', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='kommunikation',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Points for this category', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_id',
            field=models.CharField(blank=True, help_text="Autofield response id from hidden field in Typeform. Don't change this", max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='resurser',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Points for this category', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='verksamhetsstyrning',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Points for this category', max_digits=5, null=True),
        ),
    ]
