# Generated by Django 2.2.2 on 2019-07-18 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20190708_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='kommunikation',
        ),
        migrations.AlterField(
            model_name='category',
            name='survey',
            field=models.ForeignKey(blank=True, help_text='Choose what Survey this Category belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_ID',
            field=models.CharField(blank=True, help_text='Add the Question ID from Typefrom goes here', max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_id',
            field=models.SlugField(blank=True, help_text="Autofield response id from hidden field in Typeform. Don't change this", primary_key=True, serialize=False),
        ),
    ]
