# Generated by Django 2.2.2 on 2019-07-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20190718_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='kommunikation',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Points for this category', max_digits=5, null=True),
        ),
    ]
