# Generated by Django 2.2.2 on 2019-07-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20190723_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_Type',
            field=models.CharField(choices=[('text', 'short_text'), ('text', 'long_text'), ('text', 'dropdown'), ('choice.label', 'multiple_choice (single option)'), ('choice.labels', 'multiple_choice (multiple options)'), ('choice.label', 'picture_choice (single option)'), ('choice.labels', 'picture_choice (multiple options)'), ('email', 'email'), ('url', 'website'), ('file_url', 'file_upload'), ('boolean', 'legal'), ('boolean', 'yes_no'), ('number', 'rating'), ('number', 'opinion_scale'), ('number', 'number'), ('date', 'date')], help_text='Important that this is right', max_length=20),
        ),
    ]
