# Generated by Django 2.2.2 on 2019-07-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20190723_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, help_text='Choose to what Question the Answer belongs tobelongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='survey.Question'),
        ),
        migrations.AlterField(
            model_name='category',
            name='survey',
            field=models.ForeignKey(blank=True, help_text='Choose what Survey this Category belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Choose to what Category this question belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='survey.Category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_Type',
            field=models.CharField(choices=[('text', 'short_text'), ('text', 'long_text'), ('text', 'dropdown'), ('choice.label', 'multiple_choice (single option)'), ('choice.labels', 'multiple_choice (multiple options)'), ('choice.label', 'picture_choice (single option)'), ('choice.labels', 'picture_choice (multiple options)'), ('email', 'email'), ('url', 'website'), ('file_url', 'file_upload'), ('boolean', 'legal'), ('boolan', 'yes_no'), ('number', 'rating'), ('number', 'opinion_scale'), ('number', 'number'), ('date', 'date')], help_text='Important that this is right', max_length=20),
        ),
    ]
