# Generated by Django 2.2.2 on 2019-07-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20190723_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='bool_answer',
            field=models.BooleanField(blank=True, help_text='Important that this is exact', null=True),
        ),
    ]
