# Generated by Django 2.2.2 on 2019-07-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_answer_bool_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='been_calculated',
            field=models.BooleanField(default=False, help_text="If False it haven't been calculated. Helps prevent so that it dont keep adding"),
        ),
    ]
